logging:
  level:
    reactor:
      netty:
        http:
          client: ${LOGGING_LEVEL:DEBUG}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USER:toggler}
      password: ${MONGO_PASSWORD:toggler}
      database: ${MONGO_DATABASE:admin}

server:
  port: ${SERVER_PORT:8094}

